# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_custom_version_windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install doctl
        uses: ./
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          version: 1.38.0

      - name: Verify installation of correct version
        run: ls
