# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  digitalocean-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build
      run: |
        docker build . -t thetopichub913/the-topic:1.0.0
    - name: check docker images
      run: |
        docker images
    - name: docker push
      run: |
        docker push thetopichub913/the-topic:1.0.0
    #- name: ls -a via ssh
    #  uses: garygrossgarten/github-action-ssh@release
     # with:
     #   command: ls -a
     #   host: ${{ secrets.HOST }}
     #   username: ${{ secrets.USER_NAME }}
      #  privateKey: ${{ secrets.PRIVATE_KEY }}
     #   passphrase: ${{ secrets.PASS_PHRASE }}
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        # ssh host
        host: ${{ secrets.HOST }}
        # ssh key passphrase
        passphrase: ${{ secrets.PASS_PHRASE }}
        # ssh username
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
            whoami
            ls -al
