# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  digitalocean-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build
      run: |
        docker build . -t thetopichub913/the-topic:1.0.0
    - name: check docker images
      run: |
        docker images
    - name: docker push
      run: |
        docker push thetopichub913/the-topic:1.0.0
    #- name: ls -a via ssh
     # uses: garygrossgarten/github-action-ssh@release
     # with:
    #    command: ls -a
    #    host: ${{ secrets.HOST }}
    #    username: root
     #   privateKey: ${{ secrets.PRIVATE_KEY}}
    - name: Remote SSH Commands
      uses: fifsky/ssh-action@v0.0.4
      with:
        # Command to execute on the remote server.
        command: ls -a
        # Hostname or IP address of the server.
        host: 139.59.137.236
        # Username for authentication.
        user: root
        # Port number of the server.
        # port: # optional, default is 22
        # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
        key: ${{ secrets.PRIVATE_KEY}}
        # Password for authentication.
        #pass: # optional
        # SSH parameters for example: -tt.
       # args: # optional


