# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Discord test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: test
      run: |
        env
    # notifications #
    - name: Discord fail notification
      if: ${{ failure() }}
      uses: appleboy/discord-action@0.0.3
      with:
        webhook_id: "${{secrets.DISCORD_WEBHOOK_ID}}"
        webhook_token: "${{secrets.DISCORD_WEBHOOK_TOKEN}}"
        message: "Deployment failed" 
        color: "#FF0000"
  
    - name: Discord success notification
      uses: appleboy/discord-action@0.0.3
      if: ${{ success() }}
      with:
        webhook_id: "${{secrets.DISCORD_WEBHOOK_ID}}"
        webhook_token: "${{secrets.DISCORD_WEBHOOK_TOKEN}}"
        message: "Deployment successful" 
        color: 	"#00FF00"
