# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Discord test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: test
      run: |
        env

    - name: discord notification
      uses: "hugoalh/GitHubAction.SendToDiscord@v1.1.1"
      with:
        webhook_id: "${{secrets.WEBHOOK_ID}}"
        webhook_token: "${{secrets.WEBHOOK_TOKEN}}"
        message_usetexttospeech: "false"
        message_text: "Hello, world!"
